analysis:
  cluster_max_addresses: 50
  cluster_min_addresses: 2
  cluster_min_common_tokens: 2
  clusters_per_page: 3
  detail_buttons_count: 30
  known_pool_addresses:
  - 5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1
  max_concurrent_threads: 5
  ranking_size: 30
  top_holders_count: 100
bot:
  interval: 58
  min_age_days: 10
  min_market_cap: 0
  threshold: 0.05
capump:
  analysis_timeout: 180
  auto_analysis_enabled: false
  interval: 120
  max_tokens_per_batch: 10
  min_age_days: 1
  min_market_cap: 50000
  notification_enabled: true
  threshold: 0.1
jupiter:
  default_token_count: 10
  has_socials: true
  max_mcap: 1000000
  max_tokens_per_analysis: 50
  min_token_age: 3600
  period: 24h
logging:
  backup_count: 5
  level: INFO
  max_file_size: 10485760
permissions:
  allowed_chats: []
  allowed_users: []
  ca1_allowed_groups: []
proxy:
  enabled: false
  http_proxy: http://127.0.0.1:10808
  https_proxy: http://127.0.0.1:10808
