# 代币大户分析Bot - 主配置文件
# 敏感信息请在 .env 文件中配置

# 机器人基础配置（敏感信息如Token在.env中配置）
bot: 
  # Telegram相关配置在.env文件中设置

# 分析相关配置
analysis:
  cluster_max_addresses: 50
  cluster_min_addresses: 2
  cluster_min_common_tokens: 2
  clusters_per_page: 3
  detail_buttons_count: 30
  known_pool_addresses:
  - 5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1
  max_concurrent_threads: 5
  ranking_size: 30
  top_holders_count: 100

# 日志配置
logging:
  level: INFO

# 权限控制
permissions:
  ca_allowed_groups: [-1003097609656, -1002760368002, -1002593827726]

# 代理配置（可在.env中覆盖）
proxy:
  enabled: false
  http_proxy: http://127.0.0.1:10808
  https_proxy: http://127.0.0.1:10808
